[package]
name = "autocon"
version = "0.1.0"
edition = "2021"
authors = ["hamflx <a@hamflx.cn>"]
license = "MIT"

[dependencies]
thiserror = "1.0.38"
windows = { version = "0.43.0", features = ["Win32_Foundation", "Win32_System_Console", "Win32_System_Memory"] }
